Keras shape

In [3]:
import tensorflow as tf

input_shape = (2, 3)
x1 = tf.random.normal(input_shape, mean=0.0, stddev=1.0)
x2 = tf.random.normal(input_shape)
y = tf.keras.layers.Add()([x1, x2])

print(x1)
print(x2)
print(y.shape)
print(y)


tf.Tensor(
[[-0.3872332   0.31019062 -1.0423132 ]
 [ 0.307531   -0.24794483 -0.9762641 ]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[-0.25699693  1.048905   -0.2730164 ]
 [-0.5675182   0.25650707 -1.7709384 ]], shape=(2, 3), dtype=float32)
(2, 3)
tf.Tensor(
[[-0.6442301   1.3590956  -1.3153296 ]
 [-0.25998718  0.00856224 -2.7472024 ]], shape=(2, 3), dtype=float32)


In [4]:
model = tf.keras.Sequential()
rs = tf.keras.layers.Reshape((3, 4), input_shape=(12,))
model.add(rs)
s = model.output_shape  # (None, 3, 4). # (mini batch size, 3, 4)
print(s)
model.add(tf.keras.layers.Reshape((-1, 2, 2)))   # (None, 3, 2, 2)
s = model.output_shape  # (None, 3, 4)
print(s)

(None, 3, 4)
(None, 3, 2, 2)


PyTorch shape

In [6]:
import torch 

print('reshape')
x = torch.arange(24).reshape(2, 3, 4) # torch.rand(2, 3, 4)  # [2, 3, 4] 
s = x.shape
print(s)
print(x)
y = x.view(2, -1)  # [2, 12] 
print(y.shape)
print(y)
z = y.unsqueeze(0)
print('unsqueeze=', z.shape)
print(z)
z = z.squeeze(0)
print('squeeze=', z.shape)
print(z)

reshape
torch.Size([2, 3, 4])
tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
torch.Size([2, 12])
tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])
unsqueeze= torch.Size([1, 2, 12])
tensor([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
         [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]]])
squeeze= torch.Size([2, 12])
tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])


In [7]:
print('\npermute')
x = torch.arange(0, 5).reshape(1, 5)
print(x.shape)
print(x)
y = x.transpose(0, 1)  # [5, 1].
print('transpose=', y.shape)
print(y)
z = x.permute(1, 0)  # [5, 1]. 
print('permute=', z.shape)
print(z)

x = torch.arange(0, 3 * 32 * 32).reshape(3, 32, 32) # (3, 32, 32) > permute(2, 1, 0) > (32, 32, 3)
print(x.shape)
z = x.permute(2, 1, 0)
print(z.shape)


permute
torch.Size([1, 5])
tensor([[0, 1, 2, 3, 4]])
transpose= torch.Size([5, 1])
tensor([[0],
        [1],
        [2],
        [3],
        [4]])
permute= torch.Size([5, 1])
tensor([[0],
        [1],
        [2],
        [3],
        [4]])
torch.Size([3, 32, 32])
torch.Size([32, 32, 3])


In [55]:
x = torch.randint(10, (3, 4, 2))
print(x)
y = torch.argmax(x, dim=0)  # return max index, dim=collapse. 
print(y)
z = torch.argmax(x, dim=1)  # return max index, dim=collapse. 
print(z)

tensor([[[1, 7],
         [2, 5],
         [0, 3],
         [9, 8]],

        [[7, 3],
         [9, 7],
         [4, 9],
         [3, 4]],

        [[5, 8],
         [7, 9],
         [4, 7],
         [8, 5]]])
tensor([[1, 2],
        [1, 2],
        [1, 1],
        [0, 0]])
tensor([[3, 3],
        [1, 2],
        [3, 1]])


Model: "sequential_10"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_2 (Conv2D)           (None, 30, 30, 32)        896       
                                                                 
 max_pooling2d_2 (MaxPooling  (None, 15, 15, 32)       0         
 2D)                                                             
                                                                 
 conv2d_3 (Conv2D)           (None, 13, 13, 16)        4624      
                                                                 
 max_pooling2d_3 (MaxPooling  (None, 6, 6, 16)         0         
 2D)                                                             
                                                                 
 flatten_1 (Flatten)         (None, 576)               0         
                                                                 
 dense_1 (Dense)             (None, 10)              