<h4>Torch tensor operation</h4>
<h6>https://www.digitalocean.com/community/tutorials/pytorch-torch-max</h6>

In [6]:
import torch 

p = torch.randn([2, 3])
print(p)

# Get the maximum along dim = 0 (axis = 0)
max_elements, max_idxs = torch.max(p, dim=0)    # dim = reduce dim index
print(max_elements)
print(max_idxs)

tensor([[ 0.7452,  0.1951,  0.0831],
        [-0.6578,  0.2996,  1.8307]])
tensor([0.7452, 0.2996, 1.8307])
tensor([0, 1, 1])


In [8]:
# Get the maximum along dim = 1 (axis = 1)
max_elements, max_idxs = torch.max(p, dim=1)
print(max_elements)
print(max_idxs)

tensor([0.7452, 1.8307])
tensor([0, 2])


In [10]:
p = torch.randn([2, 3])
q = torch.randn([2, 3])

print("p =", p)
print("q =", q)

# Compare elements of p and q and get the maximum
max_elements = torch.max(p, q)

print(max_elements)

p = tensor([[-0.7120, -0.6302,  1.7040],
        [-0.5967, -0.0245,  0.0625]])
q = tensor([[ 0.7209,  0.2606, -1.4442],
        [-0.3405, -0.0959,  0.0240]])
tensor([[ 0.7209,  0.2606,  1.7040],
        [-0.3405, -0.0245,  0.0625]])


In [6]:
# https://linuxpip.org/pytorch-squeeze-unsqueeze/

In [7]:
# https://www.tutorialspoint.com/how-to-squeeze-and-unsqueeze-a-tensor-in-pytorch

In [13]:
# Python program to squeeze and unsqueeze a tensor
# import necessary library
import torch

# Create a tensor of all one
T = torch.ones(2,1,2) # size 2x1x2
print("Original Tensor T:\n", T )
print("Size of T:", T.size())

# Squeeze the dimension of the tensor
squeezed_T = torch.squeeze(T) # now size 2x2
print("Squeezed_T\n:", squeezed_T )
print("Size of Squeezed_T:", squeezed_T.size())

Original Tensor T:
 tensor([[[1., 1.]],

        [[1., 1.]]])
Size of T: torch.Size([2, 1, 2])
Squeezed_T
: tensor([[1., 1.],
        [1., 1.]])
Size of Squeezed_T: torch.Size([2, 2])


In [15]:
# Python program to squeeze and unsqueeze a tensor
# import necessary library
import torch

# create a tensor
T = torch.Tensor([1,2,3]) # size 3
print("Original Tensor T:\n", T )
print("Shape of T:", T.shape)
print("Size of T:", T.size())

# Squeeze the tensor in dimension o or column dim
unsqueezed_T = torch.unsqueeze(T, dim = 0) # now size 1x3
print("Unsqueezed T\n:", unsqueezed_T )
print("Size of UnSqueezed T:", unsqueezed_T.size())

# Squeeze the tensor in dimension 1 or row dim
unsqueezed_T = torch.unsqueeze(T, dim = 1) # now size 3x1
print("Unsqueezed T\n:", unsqueezed_T )
print("Size of Unsqueezed T:", unsqueezed_T.size())

Original Tensor T:
 tensor([1., 2., 3.])
Shape of T: torch.Size([3])
Size of T: torch.Size([3])
Unsqueezed T
: tensor([[1., 2., 3.]])
Size of UnSqueezed T: torch.Size([1, 3])
Unsqueezed T
: tensor([[1.],
        [2.],
        [3.]])
Size of Unsqueezed T: torch.Size([3, 1])


<h4>Reshape</h4>
</br>
<h6>https://deeplizard.com/learn/video/fCVuiW9AFzY</h6)</br>
<h6>https://www.tutorialspoint.com/how-to-flatten-an-input-tensor-by-reshaping-it-in-pytorch</h6>

In [16]:
import torch
# define a torch tensor
t = torch.tensor([[[1, 2, 3],
   [4, 5, 6]],
   [[7, 8, 9],
   [10, 11, 12]]])
print("Tensor:\n", t)
print("Size of Tensor:", t.size())

Tensor:
 tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])
Size of Tensor: torch.Size([2, 2, 3])


In [17]:
# flatten the above tensor using start_dims
flatten_t = torch.flatten(t)
print("Flatten tensor:\n", flatten_t)


Flatten tensor:
 tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])


In [18]:
flatten_t0 = torch.flatten(t, start_dim=0)
print("Flatten tensor (start_dim=0):\n", flatten_t0)

Flatten tensor (start_dim=0):
 tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])


In [20]:
t = torch.tensor([[[1, 2],
                    [3, 4]],
                    [[5, 6],
                    [7, 8]]])
print(t)
t2 = torch.flatten(t)
print(t2)
t3 = torch.flatten(t, start_dim=1)
print(t3)

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
tensor([1, 2, 3, 4, 5, 6, 7, 8])
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])


In [26]:
a = torch.rand(4, 3, 2) # size (4, 3, 2)
a = torch.arange(24) # size 
a = torch.reshape(a, (4, 3, 2))
print(a)

a_t = a.permute(1, 2, 0) # size (3, 2, 4)
print(a_t.size())
print(a_t)

a_t.view(-1, 4)

tensor([[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15],
         [16, 17]],

        [[18, 19],
         [20, 21],
         [22, 23]]])
torch.Size([3, 2, 4])
tensor([[[ 0,  6, 12, 18],
         [ 1,  7, 13, 19]],

        [[ 2,  8, 14, 20],
         [ 3,  9, 15, 21]],

        [[ 4, 10, 16, 22],
         [ 5, 11, 17, 23]]])


tensor([[ 0,  6, 12, 18],
        [ 1,  7, 13, 19],
        [ 2,  8, 14, 20],
        [ 3,  9, 15, 21],
        [ 4, 10, 16, 22],
        [ 5, 11, 17, 23]])

<h4>torch view</h4>

In [31]:
import imageio as skio
import matplotlib.pyplot as plt
import numpy as np
import torch

cat = skio.imread('cat1.jpg')
print(cat.shape)


(1536, 2048, 3)


C:\Users\MAC\AppData\Local\Temp\ipykernel_14024\1170166365.py:6: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning dissapear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  cat = skio.imread('cat1.jpg')


In [32]:
im1 = np.mean(cat, axis=2)
print(im1.shape)
im1 = im1[:618,:1000]
print(im1.shape)
im2 = np.mean(skio.imread('cat2.jpg'),axis=2)[:618,:1000]

im1.shape
im2.shape

(1536, 2048)
(618, 1000)


C:\Users\MAC\AppData\Local\Temp\ipykernel_14024\4209128490.py:5: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning dissapear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  im2 = np.mean(skio.imread('cat2.jpg'),axis=2)[:618,:1000]


(618, 1000)

In [34]:
m = np.stack([im1,im2])
m = torch.from_numpy(np.stack([m,m,m]))
print(m.size()) #torch.Size([3, 2, 618, 1100])

reshape = m.view(3,618,1000*2).numpy()
print(reshape.shape)

torch.Size([3, 2, 618, 1000])
(3, 618, 2000)
